- name: Install Hawkular Client on Pip
  pip:
    name: hawkular-client

- name: Create Group Trigger and Conditions
  hawkular_alerts_group_trigger:
   hawkular_api_hostname: "{{ hawkular_hostname }}"
   hawkular_api_port: "{{ hawkular_port }}"
   hawkular_api_auth_token: 'Basic amRvZTpwYXNzd29yZA=='
   tenant: "{{ hawkular_tenant }}"
   group_id: '{{group_id}}'
   name: 'Wildfly Memory Metrics Heap Used'
   severity: 'HIGH'
   enabled: True
   state: 'present'
   tags:
    miq.event_type: node
    miq.resource_type: miq_alert    
   conditions:
    - name: 'Min Condition'
      trigger_mode: 'FIRING'
      type: 'COMPARE'
      data_id: 'mw_heap_used'
      operator: 'GT'
      threshold: 80
    - name: 'Max Condition'
      trigger_mode: 'FIRING'
      type: 'COMPARE'
      data_id: 'mw_heap_used'
      operator: 'LT'
      threshold: 100

  register: result

- name: Update Group Trigger and Conditions
  hawkular_alerts_group_trigger:
   hawkular_api_hostname: "{{ hawkular_hostname }}"
   hawkular_api_port: "{{ hawkular_port }}"
   hawkular_api_auth_token: 'Basic amRvZTpwYXNzd29yZA=='
   tenant: "{{ hawkular_tenant }}"
   group_id: '{{ group_id}}'
   name: 'Wildfly Memory Metrics Heap Used Modified'
   severity: 'HIGH'
   enabled: True
   state: 'present'
   tags:
    miq.event_type: node
    miq.resource_type: miq_alert
    miq.event_text: trigger-modified
   conditions:
    - name: 'Test Condition'
      trigger_mode: 'FIRING'
      type: 'THRESHOLD'
      data_id: 'mw_heap_used'
      operator: 'GT'
      threshold: 0.8

- name: Delete Group Trigger
  hawkular_alerts_group_trigger:
   hawkular_api_hostname: "{{ hawkular_hostname }}"
   hawkular_api_port: "{{ hawkular_port }}"
   hawkular_api_auth_token: 'Basic amRvZTpwYXNzd29yZA=='
   tenant: "{{ hawkular_tenant }}"
   group_id: '{{ group_id }}'
   state: 'absent'
   severity: 'HIGH'
   
