#
# Copyright 2015-2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Template
metadata:
  name: Hawkular Alerts
  annotations:
    openshift.io/display-name: Hawkular Alerts
    description: Alerting subsystem for Hawkular

parameters:
- name: ROUTE_NAME
  description: What is the route to be used on Openshift?
  value:

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: hawkular-alerts
    labels:
      app: hawkular-alerts
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: hawkular-alerts
      spec:
        containers:
        - image: hawkular/hawkular-alerts
          name: hawkular-alerts
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: hawkular-alerts
    labels:
      app: hawkular-alerts
  spec:
    ports:
      - name: hawkular-alerts
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: hawkular-alerts
    type: LoadBalancer


- apiVersion: v1
  kind: Route
  metadata:
    name: hawkular-alerts
  spec:
    host:
    path:
    port:
      targetPort: hawkular-alerts
    to:
      kind: Service
      name: hawkular-alerts

- apiVersion: v1
  kind: Service
  metadata:
    name: hawkular-alerts-jmx
    labels:
      app: hawkular-alerts
  spec:
    ports:
      - name: hawkular-alerts
        port: 9010
        protocol: TCP
        targetPort: 9010
    selector:
      app: hawkular-alerts


- apiVersion: v1
  kind: Route
  metadata:
    name: hawkular-alerts-jmx
  spec:
    host: hawkular-alerts-jmx.ose.osoos.osepool.centralci.eng.rdu2.redhat.com
    path:
    port:
      targetPort: hawkular-alerts-jmx
    to:
      kind: Service
      name: hawkular-alerts-jmx


